Userstory4 createpage
HosseinKrouna/capstone-project pull request #8
Opened 2023-02-01 11:34 UTC by HosseinKrouna

2023-02-01 11:37 UTC, HosseinKrouna commented
[US-4](https://github.com/HosseinKrouna/capstone-project/issues/6)

2023-02-07 17:58 UTC, mbosselmann reviewed
Hi Hossein,
you have done a great job! :octocat:  I have many remarks for your PR, but most are improvements for your code. Nevertheless you should consider my remarks before moving further. ;)

2023-02-07 17:58 UTC, mbosselmann commented on pages/_app.js
> +    const newData = { ...data, id: v4() };
As this also works I want to remark that the documentation of uuid recommend to use the following import: `import { v4 as uuidv4 } from 'uuid';` :)

2023-02-07 17:58 UTC, mbosselmann commented on pages/_app.js
> +    return router.push(`/preview/${newData.id}`);
The return is not necessary here and can be removed.

2023-02-07 17:58 UTC, mbosselmann commented on components/EventsList.js
> +        <h2>👉New Event👈</h2>
As I know that it wasn't part of our curriculum I would recommend to nest each emoji in a `span` element for better accessibility and add some attributes. [See this article to learn more about it.](https://devyarns.com/accessible-emojis/). However, these emojis seem to have more of a decorative effect as the meaning is also clear for everyone without them. Therefore I would nest them in a span and add aira-hidden. For example:

```js
<h2><span aria-hidden="true">👉</span>New Event<span aria-hidden="true">👈</span></h2>
```

2023-02-07 17:58 UTC, mbosselmann commented on package.json
> +    "use-immer": "^0.8.1",
You do not need `use-immer`. You can remove it with this command: `npm uninstall use-immer`

2023-02-07 17:58 UTC, mbosselmann commented on pages/createEventPage.js
> +    <>
You could also think about a layout component. For further reference what I mean with layout component you can check out our art gallery app recap project. :)

2023-02-07 17:58 UTC, mbosselmann commented on pages/preview/[id].js
> +}
Instead of using optional chaining you should think about an alternative what should displayed if there is no currentEvent. The most basic solution is to display nothing:

```js
  if (!currentEvent) {
    return null;
  }
```

But it would be better to display something for the user to understand what has happened. :)

2023-02-07 17:58 UTC, mbosselmann commented on pages/votepage/[id].js
> +        <p>Creator: {currentEvent?.creator}</p>
This could also be a list with several listitems. :)

2023-02-07 17:58 UTC, mbosselmann commented on pages/votepage/[id].js
> +              <span aria-label="emoji">{voteEmoji}</span>
As I see you are using the span element for emojis already. I would also add a `role="img"` and maybe think about  more descriptive aria-label to differentiate between the different emojis.

2023-02-07 17:58 UTC, mbosselmann commented on pages/votepage/[id].js
> +      <button onClick={() => handleVoteResult()}>👉Confirm</button>
`<button onClick={handleVoteResult}>` should also be working fine. :)

2023-02-07 17:58 UTC, mbosselmann commented on pages/votepage/[id].js
> +      <StyledBackLink href="/">Back ↩︎</StyledBackLink>
I like this back link solution. Maybe you can also use this above in your `preview/[id].js`.

2023-02-07 17:58 UTC, mbosselmann commented on pages/createEventPage.js
> +            aria-labelledby="createEventForm"
I did not found the corresponding id for this aria-labelledby. Maybe the `h1`?

2023-02-08 11:18 UTC, HosseinKrouna commented
Many thanks Mareike 🙂 I hope I was able to almost fulfill your wishes

2023-02-08 14:45 UTC, NikRoe requested changes
Hi there,

looks like a promising start and I left only a few notes :)

Keep it up 🙌

2023-02-08 14:45 UTC, NikRoe commented on components/EventsList.js
> +    <StyledWrapper>
this wrapper should not wrap around the `Head` component, but only around the content that is to be displayed

2023-02-08 14:45 UTC, NikRoe commented on components/EventsList.js
> +              {entryData?.map((entry) => (
you don't need to make this line of code conditional, since you already have the same condition in line 18

```suggestion
              {entryData.map((entry) => (
```

2023-02-08 14:45 UTC, NikRoe commented on components/EventsList.js
> +      <span>
do you need this wrapping span element here?

2023-02-08 14:45 UTC, NikRoe commented on pages/votepage/[id].js
> +      <button onClick={handleVoteResult}>👉Confirm</button>
```suggestion
      <button type="button" onClick={handleVoteResult}>👉Confirm</button>
```

2023-02-08 14:45 UTC, NikRoe commented on pages/votepage/[id].js
> +      ></VoteDetails>
can be self closing:

```suggestion
      <VoteDetails
        emojiCheckmark={emojiCheckmark}
        currentEvent={currentEvent}
        entryData={entryData}
      />
```

2023-02-08 14:45 UTC, NikRoe commented on pages/preview/[id].js
> +      <StyledBackLink href="/">Back ↩︎</StyledBackLink>
Your back link should also have a text for better accessibility. If you only want to add a text for screen reader user you can add an aria-label.

2023-02-08 14:45 UTC, NikRoe commented on components/VoteDetails.js
> +      <li>Creator: {currentEvent?.creator}</li>
do all of these values have to be conditional?

2023-02-08 15:15 UTC, HosseinKrouna commented
Thanks for your time and support Nicklas 👍☺️
I have now adjusted again

2023-02-09 08:53 UTC, TariqAlQadi approved these changes

2023-02-09 08:53 UTC, TariqAlQadi commented on components/VoteDetails.js
> +      <li>Creator: {currentEvent.creator}</li>
you can map this if you want

2023-02-09 08:53 UTC, TariqAlQadi commented on components/styles/BackLink.js
> +  border-radius: 10px;
try not to use px, but its okay for now

2023-02-09 08:58 UTC, mbosselmann commented
Hi Hossein,
you did not answer all my comments about your code. Did you see everything? Because you haven't answer why you did not want to implement my remarks. 👀

2023-02-10 07:12 UTC, HosseinKrouna commented on components/EventsList.js
> +}
Good morning Mareike 😊, thanks for all your great hints. I wouldn't have thought of that so quickly😅. To be honest, I kept trying to write it as a condition, except null. In meantime and since I would like to have a condition that an alternative text is displayed if there is no event yet. I think the best way to get here is with the ternity operator. Or what do you think?

My new code looks like this

```js
      <StyledWrapper>
        <Link href="/createEventPage">
          <p>👉New Event👈</p>
        </Link>
        {entryData.length > 0 ? (
          <>
            <h2>⬇️Vote⬇️</h2>
            <StyledList>
              {entryData.map((entry) => (
                <li key={entry.id}>
                  <StyledLink href={`/votepage/${entry.id}`}>
                    <EventCard entry={entry} />
                  </StyledLink>
                </li>
              ))}
            </StyledList>
          </>
        ) : (
          <p>Nothing to vote 🤨</p>
        )}
      </StyledWrapper>
    </>

﻿﻿

2023-02-10 07:13 UTC, HosseinKrouna commented on components/EventsList.js
> +      <div>
I also think ☺️

2023-02-10 07:13 UTC, HosseinKrouna commented on components/EventsList.js
> +`;
Done

2023-02-10 07:16 UTC, HosseinKrouna commented on pages/votepage/[id].js
> +        <p>Creator: {currentEvent?.creator}</p>
Yes, they are now list items 🤓

2023-02-10 07:17 UTC, HosseinKrouna commented on pages/votepage/[id].js
> +      <button onClick={() => handleVoteResult()}>👉Confirm</button>
you are right as always 😇...done

2023-02-10 07:19 UTC, HosseinKrouna commented on pages/createEventPage.js
> +            aria-labelledby="createEventForm"
i hope i did it right

2023-02-10 09:06 UTC, mbosselmann commented on components/EventsList.js
> +}
Yeah! This looks good! 👍

2023-02-10 10:25 UTC, Long-HaHoang commented on components/VoteDetails.js
> +      <li>Creator: {currentEvent.creator}</li>
Hi Tariq,
It's a bit over-engineered to map at this point.
You have to feed the map with 6 different stings. Then you have to map over another array the get those strings somewhere.

2023-02-10 10:28 UTC, Long-HaHoang commented on components/styles/BackLink.js
> +  border-radius: 10px;
I agree with Tariq.
You can use `rem` and leave the sizing to the user.
But it will take a while to figure it out.
This might break the styling if the user increases the font-size too big.

2023-02-10 10:39 UTC, RobinWitt approved these changes
There are a few comments you haven't responded to or resolved yet, but apart from that, I think it looks good.

2023-02-10 10:39 UTC, RobinWitt commented on package.json
> +    "use-immer": "^0.8.1",
Please don't forget about that comment

2023-02-10 10:39 UTC, RobinWitt commented on pages/_app.js
> +    return router.push(`/preview/${newData.id}`);
This is not changed yet

2023-02-10 11:23 UTC, HosseinKrouna commented on components/VoteDetails.js
> +      <li>Creator: {currentEvent.creator}</li>
Thank you for your contributions. I will include the suggestions in the next user story👍

2023-02-10 11:27 UTC, HosseinKrouna commented on components/styles/BackLink.js
> +  border-radius: 10px;
I will take note of that in the next user story...thanks

2023-02-14 09:02 UTC, merged